steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/researchvault-migrate:$COMMIT_SHA', 
           '--build-arg', 'DJANGO_SETTINGS_MODULE=ResearchVault.settings',
           '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/researchvault-migrate:$COMMIT_SHA']

  # Run database migrations
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'gcr.io/$PROJECT_ID/researchvault-migrate:$COMMIT_SHA'
      - '-s'
      - '$PROJECT_ID:$_REGION:$_INSTANCE_NAME'
      - '-e'
      - 'DJANGO_SETTINGS_MODULE=ResearchVault.settings'
      - '--'
      - 'python'
      - 'ResearchVault/manage.py'
      - 'migrate'

images:
  - 'gcr.io/$PROJECT_ID/researchvault-migrate:$COMMIT_SHA'

substitutions:
  _REGION: us-central1
  _INSTANCE_NAME: researchvault-db