# Generated by Django 4.2.20 on 2025-03-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the author in the publication')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publication')),
            ],
            options={
                'verbose_name': 'Author Order',
                'verbose_name_plural': 'Author Orders',
                'ordering': ['publication', 'order'],
                'unique_together': {('publication', 'person')},
            },
        ),
        migrations.RemoveField(
            model_name='publication',
            name='read_status',
        ),
    ]
