# Generated by Django 4.2.20 on 2025-03-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_authororder_contribution_type_and_more'),
    ]

    operations = [
        # No operations - we fixed the template only
    ]