# Generated by Django 4.2.20 on 2025-03-14 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_publication_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the dissertation', max_length=500)),
                ('supervisor', models.CharField(blank=True, help_text='Additional supervisor information if different from promoter', max_length=255)),
                ('degree', models.CharField(choices=[('PhD', 'PhD'), ('Master', 'Master'), ('Bachelor', 'Bachelor'), ('Other', 'Other')], default='PhD', help_text='Type of degree', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Date when the dissertation work started', null=True)),
                ('defense_date', models.DateField(blank=True, help_text='Date of the dissertation defense', null=True)),
                ('abstract', models.TextField(blank=True, help_text='Abstract of the dissertation')),
                ('institution', models.CharField(blank=True, help_text='Institution where the dissertation was completed', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Department or faculty within the institution', max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL to the dissertation')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file of the dissertation', null=True, upload_to='dissertations/pdfs/')),
                ('keywords', models.TextField(blank=True, help_text='Keywords (comma separated)')),
                ('notes', models.TextField(blank=True, help_text='Notes about the dissertation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Author of the dissertation', on_delete=django.db.models.deletion.CASCADE, related_name='authored_dissertations', to='core.person')),
                ('copromoters', models.ManyToManyField(blank=True, help_text='Co-promoters/co-advisors of the dissertation', related_name='copromoted_dissertations', to='core.person')),
                ('promoter', models.ForeignKey(help_text='Main promoter/advisor of the dissertation', on_delete=django.db.models.deletion.CASCADE, related_name='promoted_dissertations', to='core.person')),
            ],
            options={
                'verbose_name': 'Dissertation',
                'verbose_name_plural': 'Dissertations',
                'ordering': ['-defense_date', 'title'],
            },
        ),
    ]
