# Generated by Django 4.2.20 on 2025-03-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dissertation'),
    ]

    operations = [
        # Add a new supervisor ForeignKey field
        migrations.AddField(
            model_name='dissertation',
            name='supervisor_person',
            field=models.ForeignKey(
                blank=True,
                help_text='Additional supervisor if different from promoter',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='supervised_dissertations',
                to='core.person'
            ),
        ),
    ]