# Generated by Django 4.2.20 on 2025-03-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dissertation_supervisor'),
    ]

    operations = [
        # Remove the old supervisor text field
        migrations.RemoveField(
            model_name='dissertation',
            name='supervisor',
        ),
        
        # Rename the new field to supervisor
        migrations.RenameField(
            model_name='dissertation',
            old_name='supervisor_person',
            new_name='supervisor',
        ),
    ]